### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sonV22** [mattieFM/FearAndHungerModManager#1]
When I open the game, I get an error

![image](https://github.com/mattieFM/FearAndHungerModManager/assets/142453772/361791c4-f16f-4839-b8ad-ffb3df006480)

**Comment by mattieFM** [comment]
Yeah, this isn't really officially released yet. That said it doesn't fully support Termina yet, and the if multiplayer mod is installed it will crash when playing single player.

With that in mind, the error you are getting is coming from the multiplayer mod, so it might work if you remove the multiplayer mod. It should be noted that the multiplayer mod is does not support Termina at all right now.

I know this GitHub is linked on the wiki, which it probably shouldn't be yet.

**Comment by mattieFM** [comment]
PS: what mod were you wanting to use? or did you just clone the repo to see what it was?

**Comment by sonV22** [comment]
> PS: what mod were you wanting to use? or did you just clone the repo to see what it was?

I would like to try how the cheat menu works, judging by the name, is this it? I apologize for my bad English.
I'll try uninstalling the multiplayer mod and running the game

**Comment by mattieFM** [comment]
Gotcha, that mod I only just built as a dev tool but it should work fine if you want to use it. you can press "i" to open a menu that has all the items, selecting an item in this menu will give you it. You can hit escape or "i" to close the menu.

if that's the only mod you are using the only files you need in your mods folder are as follows:
"_devTools"
"devTools.js"
"devTools.json"
"_common"

**Comment by sonV22** [comment]
> Gotcha, that mod I only just built as a dev tool but it should work fine if you want to use it. you can press "i" to open a menu that has all the items, selecting an item in this menu will give you it. You can hit escape or "i" to close the menu.
> 
> if that's the only mod you are using the only files you need in your mods folder are as follows: "_devTools" "devTools.js" "devTools.json" "_common"

Thank you very much, everything works. But if I click on the "esc" button after getting the item, I get the error again. But if press "I", it's fine.
Anyway, thank you very much.

![image](https://github.com/mattieFM/FearAndHungerModManager/assets/142453772/ef48e693-c929-4332-927b-aab07b4a7601)

**Comment by mattieFM** [comment]
Ah fair enough, honestly surprised it works in Termina at all, enjoy the mod :)
