### ISSUE TITLE
[BUG] {Character remains while playing} {priority level. [3] }

### ISSUE THREAD

**Issue by ryzzlife** [mattieFM/FearAndHungerModManager#18]
**Describe the bug**
it seems that when i skip the character intro the character remains in screen all the time.

**To Reproduce**
1. Go to 'Multiplayer'
2. Click on 'Join game'
3. Scroll down to 'character creation, select a character, skip intro'
4. See error happening

**Expected behavior**
The guy shouldn't be in the game like that lol .

**Desktop (please complete the following information):**
 - OS: [Windows 10 
 - All active mods: [only the multiplayer one]
 - Version [Beta  V1.0.0]

**Additional context**
My buddy which who i was playing experienced the same issue

![image](https://github.com/mattieFM/FearAndHungerModManager/assets/146072690/637dd882-261b-4efa-bab5-9915cb1f2989)

**Comment by mattieFM** [comment]
Fixed in Beta 1.0.2
