### ISSUE TITLE
[BUG] {Never ending battle} {priority level. [1]}

### ISSUE THREAD

**Issue by zzThiago** [mattieFM/FearAndHungerModManager#19]
Describe the bug
Never ending battle when i killed the guard, resulting in a softlock
https://github.com/mattieFM/FearAndHungerModManager/assets/135269463/4232f0bc-607b-4809-89e6-6bc18352178f

To Reproduce
Start the game 
Go to the first guard 
cut all of his limbs
Aim for the head, when he dies and the battle ends, the bug beggins.

Expected behavior
Battle should end, whit the first guard dead

Desktop (please complete the following information):
 
OS: Windows 10
All active mods: Only the multiplayer mod
Version: game version 1.4.1, mod version  beta 1.0.0

**Comment by mattieFM** [comment]
Fixed in PR 20
