### ISSUE TITLE
[BUG] {Event Flags Not working} {2}

### ISSUE THREAD

**Issue by HoMordo** [mattieFM/FearAndHungerModManager#40]
Event flags not working
I had this bug for a few days ever since i used the modloader app, the starting area of the train every time i enter the shack there, it resets all the barrels and crates and drops, and if leave for other areas, it does reset some items, also event flags like ritual circles cutscenes, finding the basement with Henryk cutscene and also resets the heads of enemies, no matter what mods i have or removes(including Cheshire's Fear & Hunger Mods) it keeps happening, also i have uninstall and reinstall the game for a hard reset but it keeps happening.

**Comment by mattieFM** [comment]
Appears to be fixed in live build.
